name: Update Opening Hours

on:
  schedule:
    - cron: '0 12 * * *'  # JST 21:00（UTC 12:00）
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fetch opening hours
        run: node fetch-hours.js
        env:
          API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          PLACE_ID: ${{ secrets.GOOGLE_PLACE_ID }}

      - name: Commit & Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/opening-hours.json
          git commit -m "🕒 営業時間自動更新" || echo "No changes"
          git push