name: Update Opening Hours

on:
  # 毎日 JST 0:05 に自動実行（UTC は 15:05）
  schedule:
    - cron: '5 15 * * *'
  # 手動実行も可能
  workflow_dispatch:

concurrency:
  group: update-hours
  cancel-in-progress: true

jobs:
  update-hours:
    runs-on: ubuntu-latest
    env:
      # リポジトリの Secrets に設定しておく
      PLACE_ID: ${{ secrets.PLACE_ID }}
      PLACES_API_KEY: ${{ secrets.PLACES_API_KEY }}

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: axios をインストール
        run: npm i axios

      - name: fetch-hours.js を実行
        run: node fetch-hours.js

      - name: JSON ファイルをコミット＆プッシュ
        if: success() && hashFiles('opening-hours.json') != ''
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add opening-hours.json
          git commit -m "chore: update opening-hours.json (auto)"
          git push
