name: Update Opening Hours

on:
  schedule:
    - cron: '0 9 * * *' # 毎日18時
  workflow_dispatch: # 手動でも実行できるように

jobs:
  update-hours:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: 依存パッケージをインストール
        run: npm install axios

      - name: fetch-hours.js を実行
        run: node fetch-hours.js

      - name: JSONファイルをコミット＆プッシュ
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add opening-hours.json
          git commit -m '⏰営業時間の自動更新' || echo "No changes to commit"
          git push origin main